import {readFileSync,writeFileSync} from 'node:fs';
import {gzipSync,gunzipSync} from 'node:zlib';
import vm from 'node:vm';
const source=readFileSync(new URL('../web/index.html',import.meta.url));
const script=source.toString().match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script); // Fail on invalid browser JavaScript before generating firmware.
const zipped=gzipSync(source,{level:9});
if(!gunzipSync(zipped).equals(source))throw Error('gzip round trip failed');
const rows=[];for(let i=0;i<zipped.length;i+=20)rows.push('  '+Array.from(zipped.subarray(i,i+20),b=>'0x'+b.toString(16).padStart(2,'0')).join(',')+',');
writeFileSync(new URL('../stm32/portal_asset.h',import.meta.url),'// Generated by tools/build-web.mjs. Edit web/index.html instead.\n#pragma once\n#include <stdint.h>\nstatic const uint8_t PORTAL_GZIP[] = {\n'+rows.join('\n')+'\n};\n');
console.log(`Portal: ${source.length} bytes HTML; ${zipped.length} bytes gzip; JS syntax and gzip roundtrip OK.`);
